fix: `strictNullCheck` TS errors integrations type (#43)
This PR fixes an issue seen by Typewriter-users where the optional types introduced in #39 cause `strictNullChecks` errors during builds:

```
integrations?: {
    All?: boolean
    AppsFlyer?: {
      appsFlyerId: string
    }
    // Adds `| undefined`
    [key: string]: boolean | { [key: string]: string } | undefined
}
```

```
yarn build
yarn run v1.6.0
$ make build
./node_modules/.bin/tsc && rsync -am --include='*.graphql' --include='*/' --exclude='*' src dist
src/lib/typewriter/generated/index.d.ts:54:5 - error TS2411: Property 'All' of type 'boolean | undefined' is not assignable to string index type 'boolean | { [key: string]: string; }'.

54     All?: boolean;
       ~~~

src/lib/typewriter/generated/index.d.ts:55:5 - error TS2411: Property 'AppsFlyer' of type '{ appsFlyerId: string; } | undefined' is not assignable to string index type 'boolean | { [key: string]: string; }'.

55     AppsFlyer?: {
       ~~~~~~~~~

Found 2 errors.
```

This PR also enables `strict` on this codebase.